// Portfolio projects with placeholder thumbnails
export const categories = [
  'All',
  'Short Form',
  'Long Form',
  'Gaming',
  'Football Edits',
  'eCommerce Ads',
  'Documentary',
  'Color Grading',
  'Anime',
  'Ads',
];

// Placeholder gradient colors for thumbnails (replaces actual video thumbs)
const thumbColors = [
  ['#6C63FF', '#3B82F6'],
  ['#3B82F6', '#A78BFA'],
  ['#A78BFA', '#6C63FF'],
  ['#1E1B4B', '#6C63FF'],
  ['#6C63FF', '#EC4899'],
  ['#3B82F6', '#10B981'],
  ['#F59E0B', '#6C63FF'],
  ['#1E1B4B', '#3B82F6'],
  ['#A78BFA', '#EC4899'],
  ['#10B981', '#3B82F6'],
  ['#EC4899', '#A78BFA'],
  ['#6C63FF', '#F59E0B'],
];

export const projects = [
  {
    id: 1,
    title: 'Urban Pulse Reels',
    category: 'Short Form',
    desc: 'High-energy Instagram Reels series for a streetwear brand. Fast cuts, sync-to-beat edits, 2.1M organic reach.',
    duration: '0:30',
    featured: true,
    colors: thumbColors[0],
    icon: '⚡',
  },
  {
    id: 2,
    title: 'FIFA World Cup Montage',
    category: 'Football Edits',
    desc: 'Cinematic tribute montage featuring iconic World Cup moments, dramatic slow-mo and custom motion graphics.',
    duration: '4:12',
    featured: true,
    colors: thumbColors[1],
    icon: '⚽',
  },
  {
    id: 3,
    title: 'Gaming Highlights — BGMI',
    category: 'Gaming',
    desc: 'Clutch kill compilation with anime-style transitions, neon effects and pulsing audio sync.',
    duration: '3:45',
    colors: thumbColors[2],
    icon: '🎮',
  },
  {
    id: 4,
    title: 'Saree Brand Ad',
    category: 'eCommerce Ads',
    desc: 'Elegant product showcase ad for a D2C ethnic wear brand. 4.2x ROAS on Meta Ads.',
    duration: '0:15',
    colors: thumbColors[3],
    icon: '🛍️',
  },
  {
    id: 5,
    title: 'Street Food Chronicles',
    category: 'Documentary',
    desc: 'A cinematic documentary exploring Mumbai\'s street food culture. Award-shortlisted at IndieFilm Fest 2024.',
    duration: '18:30',
    featured: true,
    colors: thumbColors[4],
    icon: '🎬',
  },
  {
    id: 6,
    title: 'Golden Hour Grade',
    category: 'Color Grading',
    desc: 'Luxury resort brand color treatment — warm film emulation, precise skin tone matching, DCI-P3 delivery.',
    duration: '2:00',
    colors: thumbColors[5],
    icon: '🎨',
  },
  {
    id: 7,
    title: 'Demon Slayer Fan Edit',
    category: 'Anime',
    desc: 'AMV-style tribute with frame-perfect sync, speed ramps and custom particle effects overlay.',
    duration: '3:20',
    colors: thumbColors[6],
    icon: '⚔️',
  },
  {
    id: 8,
    title: 'SaaS Product Launch Ad',
    category: 'Ads',
    desc: 'Motion graphics-heavy product ad for a B2B SaaS platform. Clean, corporate, conversion-focused.',
    duration: '0:60',
    colors: thumbColors[7],
    icon: '🚀',
  },
  {
    id: 9,
    title: 'Travel Vlog — Rajasthan',
    category: 'Long Form',
    desc: 'Full-length travel documentary with aerial footage, color grading and custom score — 800K+ views.',
    duration: '24:15',
    colors: thumbColors[8],
    icon: '🏰',
  },
  {
    id: 10,
    title: 'Valorant Ranked Highlights',
    category: 'Gaming',
    desc: 'Clean competitive highlight reel with HUD animations, custom transitions and sync cuts.',
    duration: '5:00',
    colors: thumbColors[9],
    icon: '🎯',
  },
  {
    id: 11,
    title: 'El Clásico Tribute',
    category: 'Football Edits',
    desc: 'Messi vs Ronaldo era retrospective — cinematic grade, slow-motion crowd shots, epic orchestral score.',
    duration: '6:48',
    colors: thumbColors[10],
    icon: '🏆',
  },
  {
    id: 12,
    title: 'Skincare Brand Unboxing',
    category: 'eCommerce Ads',
    desc: 'Premium unboxing content series for a D2C skincare brand — 3.8M impressions across platforms.',
    duration: '0:45',
    colors: thumbColors[11],
    icon: '✨',
  },
];
